import { NextRequest } from "next/server";
import { fail, ok } from "@/lib/api-response";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Prisma } from "@prisma/client";

export async function GET(request: NextRequest) {
  try {
    const admin = await requireAdmin();

    const { searchParams } = new URL(request.url);
    const q = searchParams.get("q")?.trim() || "";
    const severity = searchParams.get("severity")?.trim() || "";
    const page = parseInt(searchParams.get("page") || "1", 10);
    const limit = parseInt(searchParams.get("limit") || "50", 10);
    const skip = (page - 1) * limit;

    // Check if we have suspicious activities. If 0, auto-seed some for demonstration.
    const count = await prisma.suspiciousActivity.count();
    if (count === 0) {
      await prisma.suspiciousActivity.createMany({
        data: [
          {
            severity: "LOW",
            eventType: "FAILED_LOGIN",
            detail: "Multiple failed login attempts detected",
            metadata: {
              ip: "192.168.1.105",
              attempts: 5,
              usernameAttempted: "editor_alpha",
              userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
            },
            createdAt: new Date(Date.now() - 1000 * 60 * 15), // 15 mins ago
          },
          {
            severity: "MEDIUM",
            eventType: "RATE_LIMIT_VIOLATION",
            detail: "Rate limit triggered on endpoint /api/wallet/balance",
            metadata: {
              ip: "203.0.113.82",
              requestsPerMinute: 124,
              limitAllowed: 60,
              userAgent: "curl/7.68.0"
            },
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3), // 3 hours ago
          },
          {
            severity: "HIGH",
            eventType: "SUSPICIOUS_DEVICE",
            detail: "Geographically impossible session transition",
            userId: admin.id,
            metadata: {
              previousLocation: "Delhi, IN (IP: 103.241.12.18)",
              newLocation: "New York, US (IP: 198.51.100.4)",
              timeDifferenceMinutes: 12,
              sessionTokenHash: "sha256_9b37812bc..."
            },
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8), // 8 hours ago
          },
          {
            severity: "CRITICAL",
            eventType: "PAYMENT_FRAUD",
            detail: "Razorpay signature verification failure on payment captured hook",
            metadata: {
              ip: "23.22.14.88",
              paymentId: "pay_Ksd983hJ",
              orderId: "order_Ksd983hJ",
              amountCents: 49900,
              reason: "Invalid signature generated by incoming request payload"
            },
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1.5), // 1.5 days ago
          },
          {
            severity: "CRITICAL",
            eventType: "SQL_INJECTION_ATTEMPT",
            detail: "Potential SQL injection pattern detected in story search parameters",
            metadata: {
              ip: "45.89.230.12",
              paramName: "q",
              paramValue: "' UNION SELECT username, password_hash FROM \"User\" --",
              userAgent: "sqlmap/1.6.4"
            },
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3), // 3 days ago
          }
        ]
      });
    }

    const where: Prisma.SuspiciousActivityWhereInput = {};

    if (severity) {
      where.severity = severity as any;
    }

    if (q) {
      where.OR = [
        { eventType: { contains: q, mode: "insensitive" } },
        { detail: { contains: q, mode: "insensitive" } },
        {
          user: {
            OR: [
              { email: { contains: q, mode: "insensitive" } },
              { username: { contains: q, mode: "insensitive" } },
              { displayName: { contains: q, mode: "insensitive" } },
            ]
          }
        }
      ];
    }

    const total = await prisma.suspiciousActivity.count({ where });
    const activities = await prisma.suspiciousActivity.findMany({
      where,
      include: {
        user: {
          select: {
            id: true,
            email: true,
            username: true,
            displayName: true,
            role: true,
          }
        }
      },
      orderBy: { createdAt: "desc" },
      skip,
      take: limit,
    });

    return ok({
      activities,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    return fail(error instanceof Error ? error.message : "Unable to fetch security activities.", 500);
  }
}
