import { NextRequest } from "next/server";
import { z } from "zod";
import { fail, ok } from "@/lib/api-response";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import fs from "fs";
import path from "path";

const schema = z.object({
  pageName: z.string().min(1, "Page name cannot be empty"),
  layoutName: z.string().min(1, "Layout name cannot be empty")
});

function updateRegistryFile(layoutsDir: string, files: string[]) {
  const registryPath = path.join(layoutsDir, "registry.ts");
  
  let content = `// This file is auto-generated by the layouts API route. Do not edit manually.\n`;
  content += `import dynamic from "next/dynamic";\n\n`;
  content += `export const registry: Record<string, React.ComponentType<any>> = {\n`;
  
  // Sort files for deterministic generation
  const sortedFiles = [...files].sort();
  for (const file of sortedFiles) {
    const id = file.replace(/\.tsx$/, "");
    content += `  "${id}": dynamic(() => import("./${id}"), { ssr: false }),\n`;
  }
  
  content += `};\n`;
  
  let existingContent = "";
  if (fs.existsSync(registryPath)) {
    existingContent = fs.readFileSync(registryPath, "utf-8");
  }
  
  if (existingContent.trim() !== content.trim()) {
    fs.writeFileSync(registryPath, content, "utf-8");
  }
}

function scanLayouts(dirName: string) {
  const layoutsDir = path.join(process.cwd(), "components", dirName);
  const availableLayouts: Array<{ id: string; name: string; description: string }> = [];
  const layoutFiles: string[] = [];

  if (fs.existsSync(layoutsDir)) {
    const files = fs.readdirSync(layoutsDir);
    for (const file of files) {
      if (file.endsWith(".tsx") && file !== "registry.ts") {
        layoutFiles.push(file);
        const filePath = path.join(layoutsDir, file);
        const content = fs.readFileSync(filePath, "utf-8");

        // Default fallback values
        const id = file.replace(/\.tsx$/, "");
        let name = id.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
        let description = `Custom ${dirName.replace("-layouts", "")} layout.`;

        // Regex matching for exported metadata
        const nameMatch = content.match(/name\s*:\s*["']([^"']+)["']/);
        const descMatch = content.match(/description\s*:\s*["']([^"']+)["']/);

        if (nameMatch) {
          name = nameMatch[1];
        }
        if (descMatch) {
          description = descMatch[1];
        }

        availableLayouts.push({
          id,
          name,
          description
        });
      }
    }
    
    // Auto-generate registry mappings to support static bundle code-splitting
    updateRegistryFile(layoutsDir, layoutFiles);
  }
  return availableLayouts;
}

export async function GET() {
  try {
    await requireAdmin();
    
    // Fetch database page layout settings
    const layouts = await prisma.pageLayout.findMany({
      orderBy: { pageName: "asc" }
    });

    const availableLayouts = scanLayouts("home-layouts");
    const availableReaderLayouts = scanLayouts("reader-layouts");

    return ok({
      layouts,
      availableLayouts, // home layouts
      availableReaderLayouts
    });
  } catch (error) {
    return fail(error instanceof Error ? error.message : "Unable to fetch page layouts", 500);
  }
}

export async function POST(request: NextRequest) {
  try {
    await requireAdmin();
    const body = schema.parse(await request.json());

    const layout = await prisma.pageLayout.upsert({
      where: { pageName: body.pageName },
      update: { layoutName: body.layoutName },
      create: {
        pageName: body.pageName,
        layoutName: body.layoutName
      }
    });

    return ok(layout);
  } catch (error) {
    return fail(error instanceof Error ? error.message : "Unable to save page layout", 500);
  }
}

