// This file is auto-generated by the layouts API route. Do not edit manually.
import dynamic from "next/dynamic";

export const registry: Record<string, React.ComponentType<any>> = {
  "cinematic": dynamic(() => import("./cinematic"), { ssr: false }),
  "classic": dynamic(() => import("./classic"), { ssr: false }),
};
